createSqlFile <- function(sqlQuery,tableOutputFile,headers) 
{
  # todo, calculate correct linesize
  if (missing(sqlQuery)) 
        stop(" ==>  sqlQuery  not specified.")
    if (missing(tableOutputFile)) 
        stop(" ==>  tabelOutputFile not specified.")
  print(tableOutputFile)
  cat("set echo off\n", file = "sql.ctl")
  cat("set feedback off\n", file = "sql.ctl", append = T)
  cat("set verify off\n", file = "sql.ctl", append = T)
  linesize=200
  cat(paste("set linesize", linesize, "\n"), file = "sql.ctl", 
      append = T)
  cat("set termout off\n", file = "sql.ctl", append = T)
  cat("set pagesize 50000\n", file = "sql.ctl", append = T)
  cat("set null 'NA'\n", file = "sql.ctl", append = T)
  cat("set numf 999999.99\n", file = "sql.ctl", append = T)
  if (!headers)
  cat("set heading off\n",file = "sql.ctl", append = T)
  cat("set underline off\n", file = "sql.ctl", append = T)
  cat("column aar format 9990\n", file = "sql.ctl", append = T)
  cat("column mnd format 90\n", file = "sql.ctl", append = T)
  cat("column dag format 90\n", file = "sql.ctl", append = T)
  cat("column tim format 90\n", file = "sql.ctl", append = T)
  cat("column prog format 990\n", file = "sql.ctl", append = T)
  cat("column niva format 9990\n", file = "sql.ctl", append = T)
  cat("column TT_K heading TT.K\n", file = "sql.ctl", append = T)
  cat("column count(*) format 99999999\n",file = "sql.ctl", append = T)
  cat("clear breaks\n", file = "sql.ctl", append = T)
  cat("clear computes\n", file = "sql.ctl", append = T)
  cat(paste("spool",tableOutputFile,"\n",sep=" "), file = "sql.ctl", append = T)
  cat(sqlQuery,file = "sql.ctl", append = T)
  cat("spool off\n", file = "sql.ctl", append = T)
  cat("exit\n", file = "sql.ctl", append = T)
}
